### PR TITLE
Timelocked delegation

### PR DESCRIPTION
**Pull request by valeriyr**
# Description of change

There are two solution proposals:
1. The [first](https://github.com/iotaledger/kinesis/compare/7899dc9ce6..3f46479b9) includes the first two commits and can be used if we wish to change the reward logic or add events, etc.
2. The [second](https://github.com/iotaledger/kinesis/pull/162/files) one is a final proposal. We use the existing logic and it is not required to change the original source code, time-locked delegation can be implemented based on it. 

## Links to any relevant issues

Closes #130
Fixes two tasks of #134 

## Tests

Move-level integration tests.

### CODE REVIEW

**Review by miker83z — CHANGES_REQUESTED** [review]
As discussed, the `Timelock` and thus also `TimelockedStakedSui` should be non transferable.

**Review by miker83z — APPROVED** [review]
LGTM!

**Review by fijter — APPROVED** [review]
looks good 👍

**Review by samuel-rufi — APPROVED** [review]
Fantastic PR @valeriyr!

**Pull request merged**
