### PR TITLE
feat(wallet): rebrand toasters

### PR DESCRIPTION
**Pull request by evavirseda**
# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/1780

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by begonaalvarezd — COMMENTED** [review]
Amazing 🚀 you did it ⭐ 
Added a small comment about the faucet and we are good to go

**Review by VmMad — CHANGES_REQUESTED** [review]
There's an issue that happens when you click "Request tokens from faucet" too quickly many times. It shows a number. This doesn't happen with the previous toasts

[IOTA-Wallet-DEV-2.webm](https://github.com/user-attachments/assets/f54a179a-3586-4082-a721-327dba5ed840)
[IOTA-Wallet-DEV-3.webm](https://github.com/user-attachments/assets/f1a44162-e53f-4abe-8985-bca75df0e319)

Also I think it would be good to see the amount received from the faucet

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
The toasts are flickering now for me and they also dont stack, I keep pressing the button to request funds but the toasts dont show or only 1 does
[IOTA-Wallet-DEV-.webm](https://github.com/user-attachments/assets/5d6527a0-350e-4226-a7a1-2e8de69d506a)

**Review by panteleymonchuk — COMMENTED** [review]
3 questions:

1. Is it expected behaviour, when we request token, text changes in the snackbar on the fly? (see gif below)

2. Is position of snackbar right? (see gif)

3. Animation for show/hide doesn't work for me.

CleanShot 2024-09-02 at 17 47 05

**Review by panteleymonchuk — APPROVED** [review]

**Review by msarcev — APPROVED** [review]

**Review by begonaalvarezd — APPROVED** [review]

**Review by VmMad — APPROVED** [review]
Nice job!!!

**Pull request merged**
