### PR TITLE
feat(wallet): improve account finder algorithm

### PR DESCRIPTION
**Pull request by panteleymonchuk**
# Description of change

Improve search algorithm.

## Links to any relevant issues

fixes #843

~~Based on PR https://github.com/iotaledger/iota/pull/978~~

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

1. Go to `ui.html#/accounts/manage/accounts-finder/` page.
2. Press "Search" button.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by marc2332 — CHANGES_REQUESTED** [review]
Could you add more comments explaining what each function does, what X type is for, etc? It will help me (and others) review this PR and will also serve for us to understand this code in the future

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
It would be nice syncing with base to see the changes applied in this PR only 🙏🏼 at the moment github is showing the changes included in the previous PR this branch nested from

As for the review of the codebase, as discussed internally, I drafted a PR (untested) to explain my vision of the search logic with 3 algorithms which can be used for different search models (eg stardust & chrysalis portfolios) https://github.com/iotaledger/iota/pull/978 I am open for discussion on the best approach possible we can take to achieve the task, the search logic is a complicated code and we should reach consensus on the best approach to have easy, clean, modular and versatile code.

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
I suggest not mixing this PR with the coin type refactor, it makes it harder to review 🙏🏼

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — DISMISSED** [review]

**Review by marc2332 — APPROVED** [review]

**Review by begonaalvarezd — APPROVED** [review]
really amazing work 💪🏼 bravo 👏🏼

**Pull request merged**
