### PR TITLE
feat(apps-ui-kit): add list item component

### PR DESCRIPTION
**Pull request by brancoder**
# Description of change

adds List Item component

## Links to any relevant issues

resolves #882 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

### CODE REVIEW

**Review by evavirseda — CHANGES_REQUESTED** [review]
:pray:

**Review by VmMad — CHANGES_REQUESTED** [review]
Suggestions

**Review by evavirseda — CHANGES_REQUESTED** [review]
just one thought! the rest looks great :pray:

**Review by evavirseda — CHANGES_REQUESTED** [review]

**Review by evavirseda — APPROVED** [review]

**Review by VmMad — APPROVED** [review]
🎊

**Pull request merged**
