### PR TITLE
feat(iota-core, iota-config): migration.blob content validation

### PR DESCRIPTION
**Pull request by Dkwcs**
# Description of change

The migration.blob data validation.
Solution 1 implementation of #3041 .

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

`cargo run --release --bin iota genesis --working-dir test_iota_config -f --with-faucet --num-validators 1 --remote-migration-snapshots https://stardust-objects.s3.eu-central-1.amazonaws.com/iota/alphanet/latest/stardust_object_snapshot.bin.gz
`
```
cargo build --release --bin iota-test-validator
./target/release/iota-test-validator --config-dir test_iota_config
```

### CODE REVIEW

**Review by kodemartin — CHANGES_REQUESTED** [review]
Hey @Dkwcs following my first review iteration in #3054 I made a refactoring suggestion here that implies adding the validation logic in `iota_genesis_builder`.

**Review by miker83z — APPROVED** [review]
Looks good! Just a couple of small changes

**Review by kodemartin — CHANGES_REQUESTED** [review]
Hey @Dkwcs thanks for the changes. I think there is still a critical issue, plus the outstanding minor suggestions.

**Review by kodemartin — APPROVED** [review]
Looks good! Still left a few minor suggestions though that I reckon should be implemented.

**Pull request merged**
