### PR TITLE
feat(ts-sdk): Re-generate open rpc and ts sdk types derived from it

### PR DESCRIPTION
**Pull request by msarcev**
# Description of change

Commands used to generate "open-rpc":

`cargo run --package iota-open-rpc --example generate-json-rpc-spec` for the `openrpc.json`
`npx tsx scripts/generate.ts` in `sdk/typescript` to generate the `types`

For the "graphql-rpc" side what i did is the following.

Rust side:
- Added `iota_total_supply` in `crates/iota-graphql-rpc/src/types/system_state_summary.rs`
- Regenerate the schema with `cargo run --package iota-graphql-rpc generate-schema --file ./crates/iota-graphql-rpc/schema/current_progress_schema.graphql`

TS side:
- In `sdk/graphql-transport/src/queries/getLatestIotaSystemState.graphql` added the missing `iotaTotalSupply` field
- In `sdk/graphql-transport` ran `pnpm run codegen`
- Added the mapping in `sdk/graphql-transport/src/methods.ts` for `iotaTotalSupply`

(Also fixed the `stakingPoolMappingsSize` field name in `sdk/graphql-transport/src/queries/getLatestIotaSystemState.graphql` and `sdk/graphql-transport/src/methods.ts` as `codegen` and `build` was complaining about the current field name "stake" instead of "staking")

After this the build in `sdk/graphql-transport` passes.

## Links to any relevant issues

Related to https://github.com/iotaledger/iota/issues/1080

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by marc2332 — DISMISSED** [review]

**Review by begonaalvarezd — APPROVED** [review]

**Review by cpl121 — DISMISSED** [review]

**Review by kodemartin — DISMISSED** [review]

**Review by begonaalvarezd — COMMENTED** [review]
We need to re-generate https://github.com/iotaledger/iota/pull/1172 🙈

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
We need to re-generate https://github.com/iotaledger/iota/pull/1172

**Review by begonaalvarezd — APPROVED** [review]
The ts sdk build fails, we need to investigate 🕵🏼

**Review by begonaalvarezd — DISMISSED** [review]
The ts sdk build fails, we need to investigate 🕵🏼

**Pull request closed without merging**
