### PR TITLE
feat(apps-ui-kit): Add `Scrollbar` styles

### PR DESCRIPTION
**Pull request by panteleymonchuk**
## Description

By specification we can use scrollbar-width (with params `none` | `thin`) and scrollbar-color.
There is nothing about paddings etc. Better to use native instruments and don't try to invent our vehicle.

Ref to doc: https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width

image
image

## Links to any relevant issues

Fixes: #1525 

## How the change has been tested

Add `custom-scrollbar` class to any block that need to be with prettied scrollbar.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by evavirseda — CHANGES_REQUESTED** [review]
I'm not sure about creating a separate component for the scrollbar :face_with_peeking_eye:  I believe that using css styles might be sufficient for handling all of them, otherwise, we will have two types of scrollbars: the **default browser scrollbar**, which appears if no custom styling is applied, and the **custom scrollbar**, which is applied using the `CustomScrollbar` component and the css classes defined in the project :pray:

**Review by VmMad — CHANGES_REQUESTED** [review]
Scrollbar looks different on Chrome. I'll send some info about styles on slack

**Review by evavirseda — CHANGES_REQUESTED** [review]
almost there :pray:

**Review by evavirseda — APPROVED** [review]
:art: :paintbrush:

**Review by VmMad — CHANGES_REQUESTED** [review]
Needs some refinements

**Review by VmMad — APPROVED** [review]

**Review by marc2332 — COMMENTED** [review]
LGTM... but only in chromium-based browsers. In firefox it looks as a normal scrollbar. This is because you are using webkit-specific css rules.

**Pull request merged**
