### PR TITLE
refactor(wallet): Remove swaps

### PR DESCRIPTION
**Pull request by marc2332**
## Links to any relevant issues

Depends on https://github.com/iotaledger/kinesis/pull/419
Closes https://github.com/iotaledger/kinesis/issues/269

## Type of change

- Refactor

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by cpl121 — DISMISSED** [review]
LGTM

**Review by brancoder — CHANGES_REQUESTED** [review]
Remove `DEEP_BOOK_CONFIGS_UPDATED` in `features.ts`

**Review by brancoder — DISMISSED** [review]
LGTM

**Review by brancoder — DISMISSED** [review]

**Review by begonaalvarezd — COMMENTED** [review]
test approval

**Review by begonaalvarezd — DISMISSED** [review]
test approval

**Review by brancoder — DISMISSED** [review]

**Review by begonaalvarezd — COMMENTED** [review]
Should we maybe remove `deep-book-configs` from apps-backend to avoid debris?

**Review by begonaalvarezd — COMMENTED** [review]
Nice job 💪🏼 added some comments to know your opinion

**Review by brancoder — APPROVED** [review]

**Review by begonaalvarezd — APPROVED** [review]

**Pull request merged**
