### PR TITLE
feat(iota-cli): Add support for importing from seeds in IOTA CLI

### PR DESCRIPTION
**Pull request by marc2332**
Closes https://github.com/iotaledger/iota/issues/621

NOTE: I have not tried it myself (compiling the node on my laptop is a no go), so there is a chance it might not work.

### CODE REVIEW

**Review by kodemartin — DISMISSED** [review]
lgtm with a comment :sunflower:

**Review by kodemartin — APPROVED** [review]

**Review by Thoralf-M — APPROVED** [review]

**Review by Thoralf-M — CHANGES_REQUESTED** [review]
Resolving conflicts went wrong: Files changed 1,442 :joy:

**Review by miker83z — CHANGES_REQUESTED** [review]
Currently compilation is failing! Pls, check clippy in the CI

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
This PR will be automatically closed soon if we dont update it and try merging it, lets try getting these changes up to date to the latest base branch

**Review by Thoralf-M — APPROVED** [review]

**Review by begonaalvarezd — APPROVED** [review]

**Review by miker83z — APPROVED** [review]

**Pull request merged**
