### PR TITLE
feat(tooling): remove previous assets and folders

### PR DESCRIPTION
**Pull request by evavirseda**
# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

:warning: some of the icons have been replaced with ours, even though the components haven't been cleaned up, removed, or updated yet to allow us to delete the oldest `/icons` folder

fixes https://github.com/iotaledger/iota/issues/2743

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by marc2332 — APPROVED** [review]

**Review by cpl121 — CHANGES_REQUESTED** [review]
searching for `@iota/icons` in the project, I have seen that `@iota/icons` appears in the readme of `@iota/ui-icons`, we would have to modify it

conflicts too 🙏🏼

**Review by cpl121 — CHANGES_REQUESTED** [review]
I have seen that there are some icons that do not correspond to the name

icon.svg
Captura de pantalla de 2024-10-11 11-06-04

save.svg
Captura de pantalla de 2024-10-11 11-10-49

stake.svg
Captura de pantalla de 2024-10-11 11-15-05

copy.svg
Captura de pantalla de 2024-10-11 11-28-26

**Review by cpl121 — APPROVED** [review]
When the CIs are solved, for me it is already correct, nice job! 👏🏼

**Pull request merged**
