### PR TITLE
feat(wallet): rebrand connected dapps overview

### PR DESCRIPTION
**Pull request by panteleymonchuk**
Closes #1850

Depends on https://github.com/iotaledger/iota/pull/2097

### CODE REVIEW

**Review by evavirseda — CHANGES_REQUESTED** [review]
:pray: :pray:

**Review by evavirseda — CHANGES_REQUESTED** [review]

**Review by VmMad — CHANGES_REQUESTED** [review]
There are some paddings that need to be updated, sent you screenshots in slack.

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Nice work 🚀 added 2 minor comments and we are good to go

**Review by evavirseda — CHANGES_REQUESTED** [review]
almost there :pray:

**Review by begonaalvarezd — APPROVED** [review]

**Review by evavirseda — APPROVED** [review]
nice job :rocket:

**Review by VmMad — APPROVED** [review]

**Pull request merged**
