### PR TITLE
fix(tooling-general): Fix lint prettier for wallet

### PR DESCRIPTION
**Pull request by msarcev**
# Description of change

 Fix lint prettier for wallet
* Formatted everything with latest prettier
* Solved/ignored some eslint issues

**THE PRETTIER vs ESLINT resolution is split into two commits. Check the commits individually to avoid the 'noise' of prettier formating**

## Links to any relevant issues

Related to https://github.com/iotaledger/kinesis/issues/248
Related to https://github.com/iotaledger/kinesis/issues/249

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

`pnpm run lint` passes

### CODE REVIEW

**Review by marc2332 — CHANGES_REQUESTED** [review]
Could you get rid of the imports order plugin?

**Review by cpl121 — CHANGES_REQUESTED** [review]
I get an error when running the linter
>kinesis/apps/wallet/tests/storage-migration.spec.ts
  9:18  error  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

**Review by cpl121 — DISMISSED** [review]

**Review by brancoder — DISMISSED** [review]
LGTM

**Review by VmMad — DISMISSED** [review]
lgtm

**Review by marc2332 — APPROVED** [review]
LRGTMLMIA

**Review by brancoder — APPROVED** [review]
LGTM

**Review by cpl121 — APPROVED** [review]

**Pull request merged**
