### PR TITLE
Revert `AuthorityStore` deprecated functions to fix `AuthorityStore::multi_get_transaction_checkpoint`

### LINKED ISSUE #4154: [iota-core]: `AuthorityStore::multi_get_transaction_checkpoint` returns only current epoch checkpoints
## Description

#3829 removed `AuthorityStore` methods that seemed to be deprecated, leading to [this refactoring](https://github.com/iotaledger/iota/pull/3829/files#diff-4cb78a0dfdcac54d592e9e18863cd34b409666bc5b9f102926d4f69ecfe21254R4995-R5002) affecting the `<AuthorityStore as TransactionKeyValueStoreTrait>::mutl_get_transaction_checkpoint` implementation that now uses the `AuthorityPerEpochStore` tables to fetch the required information:

https://github.com/iotaledger/iota/blob/fb9c37be792d4d63983839f3061e98367ad9cd75/crates/iota-core/src/authority.rs#L4994-L5003

This store however is reset on every epoch changes, and so querying the `AuthorityStore` for the checkpoint corresponding to transactions executed in previous epochs returns `None`.

This affects queries in the JSON-RPC server, and in particular 

https://github.com/iotaledger/iota/blob/fb9c37be792d4d63983839f3061e98367ad9cd75/crates/iota-json-rpc/src/read_api.rs#L789-L798

### How to reproduce

Refactored the JSON-RPC tests to assert the transaction-block timestamp in the [sc-platform/fix-transaction-block-checkpoint](https://github.com/iotaledger/iota/tree/sc-platform/fix-transaction-block-checkpoint).

1. `cargo nextest run -p iota-json-rpc-tests -E "test(#get_transaction_block)"`: The test should fail
2. `git checkout d891762d9fae5f70ca19c489c145dd68948a6e3a~`: This checks out the code before #3829 
3. `cargo nextest run -p iota-json-rpc-tests -E "test(#get_transaction_block)"`: The test should pass

### PR DESCRIPTION
**Pull request by bingyanglin**
# Description of change

Together with @semenov-vladyslav to investigate the `AuthorityStore` deprecated codes again, and in order to enable get the `CheckpointSequenceNumber` by the transaction digest, the old deprecated codes need to be reverted, because there is no other tables storing the relationship between the `digest` and `epochId`, or `digest` and `CheckpointSequenceNumber` in old epochs.  Also the `deprecated_multi_get_transaction_checkpoint`/`deprecated_get_transaction_checkpoint` /`deprecated_insert_finalized_transactions`/`executed_transactions_to_checkpoint`/`checkpoint_cache` are coupled together. The easiest/safest way might be just to revert them back.

## Investigation

The error is triggered in JSON RPC `ReadApi` impl of `get_transaction_block`: the API response contains checkpoint sequence number and timestamp (of the checkpoint) which are fetched from `AuthorityPerpetualTables::executed_transactions_to_checkpoint` DB table via a number of traits and wrappers. The table is not used for any other purposes and was marked as deprecated (together with a number of related functions and trait methods that support this table) in favor of `AuthorityEpochTables::executed_transactions_to_checkpoint` which gets cleared after each epoch. The reason for deprecation is unclear. Maybe, the JSON RPC ReadApi was expected to change (eg. get rid of checkpoint sequence number), or the implementation was expected to change and not use the mentioned table.

1. Right now we do not wish to change JSON RPC ReadApi.
2. We can't reimplement it another way (eg. fetch checkpoint info from another table); there is `AuthorityState::rest_index` that might have the required info (it seems to be duplicated), but it is only optionally enabled, so we can't rely on it unconditionally.
3. The access to the table is hidden with traits and wrappers, so it's not possible to simplify access to it and still get rid of methods marked as deprecated.

So the only reasonable option is to revert the RP that removed the table and deprecated API. And rename functions to make it clearer that the checkpoint info is fetched from *perpetual* table and add a few comments explaining these few implementation details.

As for the testnet the simplest solutions is to resync nodes from genesis.

## Links to any relevant issues

Fixed #4154

## Type of change

- Bug fix (a non-breaking change which fixes an issue)

### Local Testing

Passed the testing `cargo nextest run -p iota-json-rpc-tests -E "test(#get_transaction_block)"` locally.

```bash
 Nextest run ID a45927f8-cf75-464b-a4ea-a5110d5a6d8e with nextest profile: default
    Starting 1 test across 10 binaries (148 tests skipped)
        PASS [  14.656s] iota-json-rpc-tests::read_api get_transaction_block
```
 ### Sync from Genesis Testing
 
 1. Prepare empty `db/live` folder
 2. Build this branch and run `cargo run --release --bin iota-node -- --config-path fullnode.yaml`
 3. Successfully sync without crashing
 4. Query the old checkpoint and it returns checkpoints belonging to epoch 0.
 ```bash
curl 'http://iota-test-node-0.iota.works:9000/' \
  -H 'content-type: application/json' \
  --data-raw '{"jsonrpc":"2.0","id":12,"method":"iotax_queryTransactionBlocks","params": [
    {
      "filter": {"FromAddress": "0x0000000000000000000000000000000000000000000000000000000000000000"},
      "options": {"showInput": true}
    },
    null,
    10,
    false
  ]}' | json_pp | grep checkpoint
```
6. Get the correct output
```bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11637  100 11375  100   262  26006    599 --:--:-- --:--:-- --:--:-- 26629
            "checkpoint" : "0",
            "checkpoint" : "4",
            "checkpoint" : "1",
            "checkpoint" : "2",
            "checkpoint" : "2",
            "checkpoint" : "6",
            "checkpoint" : "8",
            "checkpoint" : "11",
            "checkpoint" : "13",
            "checkpoint" : "16",
```
 
 ### Sync in the middle of the epoch testing
 
1. Use the `iotaledger/iota-node:v0.7.2-rc` image to sync to the last checkpoint.
2. Shut the node down, and remain all the `live` folder
3. Apply this reverting change, build and run `cargo run --release --bin iota-node -- --config-path fullnode.yaml`
5. Successfully sync without crashing
6. Query the old checkpoint and it works
```bash
  curl 'http://iota-test-node-0.iota.works:9000/' \
  -H 'content-type: application/json' \
  --data-raw '{"jsonrpc":"2.0","id":12,"method":"iotax_queryTransactionBlocks","params": [
    {
      "filter": {"FromAddress": "0x0000000000000000000000000000000000000000000000000000000000000000"},
      "options": {"showInput": true}
    },
    "7FoK3eUdLeRhpsyCyMqEJ5coKX2A4eAhrA3AqKWJWvex",
    2,
    false
  ]}' | json_pp | grep checkpoint
```  
7. Get the correct output
```bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2301  100  1998  100   303   3116    472 --:--:-- --:--:-- --:--:--  3584
            "checkpoint" : "1075228",
            "checkpoint" : "1075228",
```

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by muXxer** [comment]
As discussed in the call, if those things are actually needed and not deprecated, please remove all "deprecated" comments and function names, and add a proper description why the database table is needed.

Then please sync the state from genesis with an old commit of the codebase, then apply this fix and restart the node to check if the node crashes, or if the newly added table works fine.

@alexsporn  We should discuss if a "migration step or tool" is needed to fill that info in the perpetual table, or if the lack of the info for the old transactions is not that big of a problem. In my opinion it would get pruned at some point anyway, or nodes that want to keep all history could simply resync from genesis after applying that fix, to have the fixed state.

**Comment by bingyanglin** [comment]
> Then please sync the state from genesis with an old commit of the codebase, then apply this fix and restart the node to check if the node crashes, or if the newly added table works fine.

Thanks @muXxer for the test plan, I addressed them and did 3 different testings in [7347932](https://github.com/iotaledger/iota/pull/4164/commits/73479325ab69f9d195250ca6009a82079454c545) locally. All of them passed, and I put the details [here](https://github.com/iotaledger/iota/pull/4164#issue-2676015438). @semenov-vladyslav will add comments and do renaming, then I will test the new commit again. Also need to check if we can query the tx digest which belongs to the previous epoch.
Updated: [d32c948](https://github.com/iotaledger/iota/pull/4164/commits/d32c948c60b054505ba99ed39f29ab81a68dc0d7) also passed the three same scenarios.

**Review by semenov-vladyslav — APPROVED** [review]

**Review by muXxer — APPROVED** [review]

**Review by kodemartin — COMMENTED** [review]
The test patch documented in #4154 is not actually merged on `develop`. I will push a more polished version promptly here if you don't mind.

**Review by kodemartin — APPROVED** [review]
Added the test with 60c8182faf. Ran it locally, so once the CI passes this is good to go

**Comment by muXxer** [comment]
After an in person discussion with @miker83z we decided to investigate first how this information is fetched via graphql RPC, before we reintroduce these mappings in the database just for the json-rpc. Maybe there is a way without using the table.

**Comment by semenov-vladyslav** [comment]
Graphql uses iota-indexer to process queries, it is the job of iota-indexer to maintain the DB, iota-indexer runs iota-node with rest_api enabled which in turn enables `AuthorityState::rest_index` , which maintains its own DB that stores the proper table. It's possible to fetch checkpoint from a DB maintained by `rest_index`, but it is not always enabled, its type is `Option<Arc<RestIndexStore>>` and is enabled from config flag.

**Comment by kodemartin** [comment]
> After an in person discussion with @miker83z we decided to investigate first how this information is fetched via graphql RPC, before we reintroduce these mappings in the database just for the json-rpc. Maybe there is a way without using the table.

GraphQL uses the indexer database, as does the Indexer RPC that return the expected information. The node tables do not enter the equation.

**Pull request merged**
