### PR TITLE
feat(wallet): rebrand "welcome" page

### PR DESCRIPTION
**Pull request by panteleymonchuk**
# Description of change

image

## Links to any relevant issues

Closes #1185
Depends on #1474

## How the change has been tested

Upload your wallet and click the icon. Expected behavior: the welcome page should open.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by muXxer — APPROVED** [review]

**Review by brancoder — CHANGES_REQUESTED** [review]
CI is failing :pray:

**Review by evavirseda — CHANGES_REQUESTED** [review]
it needs to be synced with `develop` so that all the styles work properly :pray: conflicts!

**Review by evavirseda — CHANGES_REQUESTED** [review]
also this previous [comment](https://github.com/iotaledger/iota/pull/1475#discussion_r1696957664) has not been resolved :pray:

**Review by evavirseda — APPROVED** [review]
lgtm :rocket:

**Review by brancoder — APPROVED** [review]
LGTM

**Pull request merged**
