### PR TITLE
feat(explorer)!: refactor folder modularity and improve imports

### PR DESCRIPTION
**Pull request by VmMad**
# Description of change

Folder structure needed a refactor to follow our coding convention.

## Links to any relevant issues

Fixes #325 

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by marc2332 — APPROVED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]
Hold on
image

**Review by marc2332 — COMMENTED** [review]
The import is not correct it seems?

Ours: 
```js
import Highlight, { defaultProps, Prism } from 'prism-react-renderer';
```

What it should look like:

Ours: 
```js
import { Highlight, defaultProps, Prism } from 'prism-react-renderer';
```

**Review by marc2332 — DISMISSED** [review]
I'll fix the error in another PR as it has nothing to do with your changes

**Review by msarcev — APPROVED** [review]
LGTM as build,lint,test passes 👍🏻

**Review by marc2332 — APPROVED** [review]

**Pull request merged**
