### PR TITLE
refactor(wallet): Remove zk-login

### PR DESCRIPTION
**Pull request by brancoder**
# Description of change

Removes all zk login related code
resolves https://github.com/iotaledger/iota/issues/267

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by marc2332 — DISMISSED** [review]

**Review by cpl121 — CHANGES_REQUESTED** [review]
Conflicts 🙏🏼

**Review by marc2332 — DISMISSED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]
I think you have added some zkLogin files again after resolving the conflicts, see for example these:

```

        deleted:    apps/wallet/src/background/accounts/zklogin/ZkLoginAccount.ts
        deleted:    apps/wallet/src/background/accounts/zklogin/current-epoch.ts
        deleted:    apps/wallet/src/background/accounts/zklogin/providers.ts
        deleted:    apps/wallet/src/background/accounts/zklogin/utils.ts
        deleted:    apps/wallet/src/ui/app/components/accounts/ZkLoginAccountWaringModal.tsx
        deleted:    apps/wallet/src/ui/app/components/accounts/ZkLoginButtons.tsx
        
```

There might be more tho

**Review by cpl121 — CHANGES_REQUESTED** [review]
1 minimal thing 🙏🏼

**Review by marc2332 — DISMISSED** [review]
lgtm, just do the lockfile thing that cesar mentioned

**Review by cpl121 — DISMISSED** [review]

**Review by msarcev — COMMENTED** [review]
But why format all the `package.json`s to tabs again inside this PR ?
This is something that we are trying to fix so that building "doesnt format to tabs anymore".

**Review by begonaalvarezd — APPROVED** [review]
epic

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
just a tiny comment above and lgtm, really good work

**Review by cpl121 — CHANGES_REQUESTED** [review]
conflicts 🙏🏼

**Review by begonaalvarezd — DISMISSED** [review]

**Review by cpl121 — APPROVED** [review]
NJ 👏🏼

**Review by begonaalvarezd — APPROVED** [review]

**Pull request merged**
