### PR TITLE
feat(wallet-dashboard): Add basic Notification manager

### PR DESCRIPTION
**Pull request by msarcev**
# Description of change

- Added a `Notification` component that should be hooked somewhere (in one place)
- Toast popups are "managed" through a zustand store.
- Added a `useNotifications` react hook for convenience (hooks into `addNotification`)

## Links to any relevant issues

Closes https://github.com/iotaledger/kinesis/issues/287

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change CAN been tested

* Add a button somewhere yourself which calls `addNotification` from `useNotificationStore`
* Paste the following code in the body of `Notifications` (src/components/notifications.tsx L52):
```
	const addNotification = useNotificationStore((state) => state.addNotification);

	useEffect(() => {
		const to1 = setTimeout(() => {
			addNotification("Hi! I'm an info notification", NotificationType.Info, 6000);
		}, 1000);

		const to2 = setTimeout(() => {
			addNotification("Hi! I'm a success notification", NotificationType.Success, 4000);
		}, 1500);

		const to3 = setTimeout(() => {
			addNotification("Hi! I'm a warning notification", NotificationType.Warning);
		}, 2000);

		const to4 = setTimeout(() => {
			addNotification("Hi! I'm an error notification", NotificationType.Error, 2000);
		}, 2500);

		return () => {
			clearTimeout(to1);
			clearTimeout(to2);
			clearTimeout(to3);
			clearTimeout(to4);
		};
	}, [addNotification]);
```

### CODE REVIEW

**Review by cpl121 — DISMISSED** [review]
Didn't we mention using this library in Monday's meeting?
https://www.npmjs.com/package/@boxfish-studio/react-notification-manager 🤔

**Review by marc2332 — DISMISSED** [review]

**Review by marc2332 — COMMENTED** [review]
LGTM but could you maybe add a dummy hook to avoid having to `const addNotification = useNotificationStore((state) => state.addNotification); ?

```tsx
const addNotification = useAddNotification();
```

or maybe something more generic:

```tsx
const { addNotification } = useNotifications();
```

**Review by marc2332 — DISMISSED** [review]
the rest lgtm

**Review by cpl121 — DISMISSED** [review]
LGTM
just conflicts 🙏🏼

**Review by cpl121 — APPROVED** [review]

**Review by marc2332 — APPROVED** [review]

**Pull request merged**
