### PR TITLE
feat(wallet-dashboard): switch accounts & delete permissions.

### LINKED ISSUE #669: [Task (tooling/wallet)]: Investigate a way to refresh connected accounts from dapps
At the moment, if a user connects to a dapp, the wallet requests the user to how many accounts it wants to connect to. Once the dapp is connected to X accounts, if a user adds a new account to the wallet, in order to be able to add this account to the wallet the user must navigate within the browser extension to apps > connected > dappName and decide to disconnect so it can connect again in the dapp and pull in the new accounts. 

Given that we will have an accounts finder available in the wallet, it would be interesting styding if this is a UX friction we want to solve, and if so, how. 

To study it, we can create an internal RFC where we document the problem we intend to solve, which solutions could be implement, what is the impact of each, and use this document to make a decision out of it

### PR DESCRIPTION
**Pull request by panteleymonchuk**
# Description of change

Switching between accounts works properly by default. However, if user signed and selected one account, he can't select more accounts for switching. For this case added function "Deactivate All"

Note: I didn't apply eslint --fix to seen only real changes.

## Links to any relevant issues

Close https://github.com/iotaledger/iota/issues/669

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

1. Click "Deactivate all".
2. Try to connect wallet again.

Expected: select permissions and accounts again.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by evavirseda — COMMENTED** [review]
It should show all my accounts in this switcher, right? I think something's not working correctly :pray: 
Screenshot from 2024-05-29 14-01-20
Screenshot from 2024-05-29 14-00-54

**Review by msarcev — CHANGES_REQUESTED** [review]
- The code has commented sections in multiple files, please polish it to a mergeable state first.
- We should probably add tests in `dapps-kit` for the introduced hooks

**Review by marc2332 — CHANGES_REQUESTED** [review]
sorry for making it so long!

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]
You still have some pending reviews (not just the ones I pinged you)

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]
Very small details, the rest LGTM

**Review by marc2332 — DISMISSED** [review]
LGTM

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — APPROVED** [review]
a38a916b4350a61e

**Review by VmMad — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
