### PR TITLE
feat(tooling-explorer): Rebrand Homepage feeds

### PR DESCRIPTION
**Pull request by marc2332**
DEPENDS ON https://github.com/iotaledger/iota/pull/2072 !!!!!!!!
Closes https://github.com/iotaledger/iota/issues/1889
Closes https://github.com/iotaledger/iota/issues/1891
Closes https://github.com/iotaledger/iota/issues/1890

Refactors `TableCard` to use ui-kit's Table and adapts the homepage feeds to the new API (some other tables got broken though, they will be fixed in other PRs)

### CODE REVIEW

**Review by evavirseda — CHANGES_REQUESTED** [review]

**Review by panteleymonchuk — CHANGES_REQUESTED** [review]

**Review by evavirseda — CHANGES_REQUESTED** [review]
:female_detective:

**Review by evavirseda — COMMENTED** [review]
last comment, I promise! :pray:iIn the previous code, `sequenceNumber` and `checkpointSet` are also links... maybe we should open an issue to review the logic if needed, or handle it in this pr, I’m not sure which is best, but we shouldn’t lose track of this approach right?

**Review by evavirseda — APPROVED** [review]
:rocket:

**Review by brancoder — CHANGES_REQUESTED** [review]
LG just a couple of questions:

1.  Should data in table, like digest and sender addres,  be truncated like it is in te explorer currently? And also currently time is ticking seconds but in your PR its changed to timestamp, or is this out of the scope of this PR
image
image

2.  Should view all button  and total label, at the bottom of the table, be updated to match figma? Also bottom of the table looks a bit weird with multiple borders.
 
image

figma:
image

**Review by brancoder — APPROVED** [review]
LGTM :confetti_ball:

**Review by panteleymonchuk — APPROVED** [review]

**Pull request merged**
