### PR TITLE
feature: build and compile native tokens from a template

### PR DESCRIPTION
**Pull request by samuel-rufi**
# Description of change

This PR provides a native token template and a way to build and compile packages from it.

How it works in general:

A prepared native token package with variables to be replaced, serves as a starting point. It will automatically:

1) Copy over the prepared package template.
2) Replace desired variables (like package name, addresses, ...)  in the Move.toml file.
3) Replace desired variables in the .move module file.
4) Compile and return the package.

Try it out by running the provided example.

Note: Currently, the native token template makes use of `coin::create_currency`. This will be later replaced with functions from https://github.com/iotaledger/kinesis/issues/127.

## Links to any relevant issues

Fixes https://github.com/iotaledger/kinesis/issues/108

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Built packages pass the Sui Move compiler. Additional tests for copying and converting foundries have been provided.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by kodemartin — CHANGES_REQUESTED** [review]
Hey @samuel-rufi, it looks good! Nevertheless I have made some minor suggestions to help improve the API. Also please:

1. Run and satisfy `cargo clippy`.
2. Since these are new modules, we should probably use the IOTA license header exclusively.
3. Provide documentation for all public API.

Moreover,  we have to ask ourselves whether there is reason to maintain the source code or not. Do you see any reasons the on-chain versions won't suffice? cc. @lzpap @fijter 

If so, probably we should nest the source-code generation and compilation logic in a different location (e.g. `sui-framework/packages` and integrate the building logic in the `build.rs`). This would imply an additional manual pre-processing step on the stardust ledger snapshot, before the generation of objects. 

I reckon however that we can live without the source code. Simpler implementation, without bloating `sui-genesis-builder` with artifacts.

**Review by fijter — DISMISSED** [review]
Good work Sam :)

**Review by kodemartin — CHANGES_REQUESTED** [review]

**Review by kodemartin — APPROVED** [review]
Ok @samuel-rufi I think you covered all of my comments.

Before you eventually merge, I would suggest  squashing all the review changes (at least). 

Good job!

**Review by miker83z — CHANGES_REQUESTED** [review]
Good work following all suggestions! I just have a couple more left.

**Review by kodemartin — CHANGES_REQUESTED** [review]
@samuel-rufi I missed that one: https://github.com/iotaledger/kinesis/pull/146#discussion_r1585999328

Should be small change though.

**Review by miker83z — APPROVED** [review]

**Review by kodemartin — APPROVED** [review]

**Pull request merged**
