### PR TITLE
feat: bump iota to v0.8.0-alpha

### PR DESCRIPTION
**Pull request by lzpap**
# Description of change

Bumping iota to the `0.8.0-alpha`, which contains protocol version 2.

### CODE REVIEW

**Review by thibault-martinez — APPROVED** [review]
There is a version in external-crates/move/crates/move-analyzer/editors/code/scripts/create.sh, not sure if it's supposed to be part of the release process or not

**Comment by valeriyr** [comment]
> There is a version in external-crates/move/crates/move-analyzer/editors/code/scripts/create.sh, not sure if it's supposed to be part of the release process or not

Oops, sorry, I closed the PR instead of creating a comment.
This script can be run manually to build the extension using the binaries of the specified version. Any existing version can be used, so updating it is possible but not required.

**Comment by valeriyr** [comment]
This file was updated in the previous PR:
https://github.com/iotaledger/iota/blob/55c14e81969aeecfde3538063e66bca5fe06286b/sdk/typescript/src/version.ts#L8
Should it be updated here?

**Review by valeriyr — APPROVED** [review]

**Comment by lzpap** [comment]
> This file was updated in the previous PR:
> 
> https://github.com/iotaledger/iota/blob/55c14e81969aeecfde3538063e66bca5fe06286b/sdk/typescript/src/version.ts#L8
> 
> 
> Should it be updated here?

It's not needed any more, @begonaalvarezd and the sdk release will take care of it.

**Review by alexsporn — APPROVED** [review]

**Review by sergiupopescu199 — APPROVED** [review]

**Pull request merged**
