### PR TITLE
feat: Staking reward generation through inflation

### PR DESCRIPTION
**Pull request by valeriyr**
# Description of change

This PR introduces a staking reward generation mechanism based on IOTA inflation/deflation.

The following changes were made:

1. `IotaTreasuryCap` was introduced to protect the IOTA token from being minted/burnt by an unauthorized address. It is placed in the `IotaSystemStateInnerV2` structure and can be used only by the system address in the `iota_system::iota_system_state_inner` module. Also, changed the executor conservation checks to make it possible to mint/burn tokens during epoch change transactions.
2. The config parameters for staking were changed according to the [table](https://github.com/iotaledger/iota/issues/944).
3. Stake subsidy was disabled by changing the related parameters. Created an additional issue #1001.
4. Disabled the storage fund reinvestment rate in `iota-protocol-config`. The logic is partially removed from the Move framework. Created an additional issue #1005.
5. The `storage_rebate_rate` protocol parameter was set to `100%`.
6. The staking rewards leftovers are burnt instead of to be stored in `storage_fund`.
7. Removed the part of the validator reward that was calculated based on the `storage_fund` balance.
8. Introduced a constant target reward rate per epoch for validators and burn/ mint new tokens depending on `computation_reward`.
9. Integrated the inflation changes with the genesis builder.

## Links to any relevant issues

fixes #153 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Autotests.

### CODE REVIEW

**Review by miker83z — CHANGES_REQUESTED** [review]
Great work guys! I think it is very clean given the amount of changes requested. 

I have left just some comments for possible minor changes for discussion below!

**Review by miker83z — DISMISSED** [review]
LGMT! Just a suggestion for the constants below. 

Then it would be nice to fix some CI's errors (at least clippy and [this](https://github.com/iotaledger/iota/actions/runs/9940536631/job/27457629887?pr=1052))

**Review by lzpap — DISMISSED** [review]
Looks good to me! We shall test if we can run `iota-test-validator` with the test snapshot coming from #1182.

**Review by lzpap — DISMISSED** [review]

**Review by miker83z — DISMISSED** [review]

**Review by miker83z — APPROVED** [review]

**Review by lzpap — APPROVED** [review]
It was a big feature, thanks for coordinating it @valeriyr!

**Pull request merged**
