### PR TITLE
feat(sc-platform): Remove stake subsidy fund

### PR DESCRIPTION
**Pull request by PhilippGackstatter**
# Description of change

Remove the stake subsidy fund and all data and fields derived from it.

- Fixes the calculate APY API by considering exchange rates from all epochs instead of only those after the `stake_subsidy_start_epoch`.
- Also removes some unused insta snapshots in `crates/iota-swarm-config/tests/snapshots`, which I discovered because they contain a "subsidy" string.
- Ignores subsidy strings in `iota-replay` since those tests are ignored right now due to the rename.
- `iota-graphql-rpc` docs were regenerated.

## Links to any relevant issues

fixes issue #1001 

## How the change has been tested

- `cargo test -p iota-indexer`
- `cargo test -p iota-genesis-builder`
- `cargo run --bin iota-test-validator`
- `cargo run --bin iota move test --path crates/iota-framework/packages/iota-system/Move.toml`
- `cargo test --features pg_integration {test_single_all_examples_structure_valid,test_bad_examples_fail}`

### CODE REVIEW

**Review by miker83z — DISMISSED** [review]
LGTM! 

There is just a fix coming from clippy that can be done here or in the subsequent PRs!

**Review by miker83z — APPROVED** [review]

**Review by valeriyr — APPROVED** [review]
LGTM!

**Review by lzpap — COMMENTED** [review]
Created an issue so we don't forget the framework snapshot update @PhilippGackstatter https://github.com/iotaledger/iota/issues/1545

**Review by samuel-rufi — APPROVED** [review]

**Review by Thoralf-M — APPROVED** [review]

**Review by kodemartin — APPROVED** [review]
lgtm

**Review by Thoralf-M — CHANGES_REQUESTED** [review]
error[E0432]: unresolved import `iota_types::iota_system_state::iota_system_state_inner_v1::StakeSubsidyV1`
    --> crates/iota-json-rpc/src/coin_api.rs:1313:45
     |
1313 |                     IotaSystemStateInnerV1, StakeSubsidyV1, StorageFundV1, SystemParametersV1,
     |                                             ^^^^^^^^^^^^^^ no `StakeSubsidyV1` in `iota_system_state::iota_system_state_inner_v1`

error[E0560]: struct `iota_types::iota_system_state::iota_system_state_inner_v1::SystemParametersV1` has no field named `stake_subsidy_start_epoch`
    --> crates/iota-json-rpc/src/coin_api.rs:1476:21
     |
1476 |                     stake_subsidy_start_epoch: Default::default(),
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^ `iota_types::iota_system_state::iota_system_state_inner_v1::SystemParametersV1` does not have this field
     |
     = note: all struct fields are already assigned

error[E0560]: struct `iota_types::iota_system_state::iota_system_state_inner_v1::IotaSystemStateInnerV1` has no field named `stake_subsidy`
    --> crates/iota-json-rpc/src/coin_api.rs:1488:17
     |
1488 |                 stake_subsidy: StakeSubsidyV1 {
     |                 ^^^^^^^^^^^^^ `iota_types::iota_system_state::iota_system_state_inner_v1::IotaSystemStateInnerV1` does not have this field

**Review by kodemartin — CHANGES_REQUESTED** [review]
All failing tests should pass actually

https://github.com/iotaledger/iota/actions/runs/10195461825?pr=1186

**Review by Thoralf-M — APPROVED** [review]

**Review by kodemartin — APPROVED** [review]

**Pull request merged**
