### PR TITLE
feat(sui-framework): Labeled timelocks Move part

### PR DESCRIPTION
**Pull request by valeriyr**
# Description of change

**1. Labelling shall be supported by `Timelock<T>` objects.** Added a `label` member to the `Timelock` object.
**2. Label creation shall be exclusive, meaning a certain label can only be produced and added to an object by a given entity.** It is achieved by the `LabelerCap` capability that should be sent to the authority address that can produce labels.
**3. Labels from one entity must be clearly distinguishable from labels of other entities.** It is implemented by typed labels. To add a new label is it necessary to create a new module and create a `LabelerCap` by consuming OTW.
**4. Adding a label to a Timelock object can only be carried out by the creator of that object.** The `LabelerCap` capability owner can add labels only in the `lock_with_label` function.
**5. Labels need to persist over staking/unstaking activities. When `Timelock<Balance<IOTA>>` funds are staked, the label shall be carried over to `TimelockedStakedIota`, and upon withdrawal, the not-yet expired timelock object shall persist the label.** It is done by migrating the labels between the `Timelock` and `TimelockedStakedSui` objects.
**6. All timleocked funds coming from the `merge` shall be labeled already in the genesis.** TODO in the next PR.
**7. Labels on timelock objects are an optional feature.** The `label` member is an `Option` and is not created for simple timelocks.
**8. Timelock objects can be joined only if their labels match.** The timelocks with the same labels can be joined.

## Links to any relevant issues

Relates to #443 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Automated tests

### CODE REVIEW

**Review by miker83z — DISMISSED** [review]
LGTM! 

I think the current status of the PR is "Ready" and the remaining task ("All timleocked funds coming from the merge shall be labeled already in the genesis") could be done with another PR.

**Review by miker83z — DISMISSED** [review]

**Review by miker83z — DISMISSED** [review]
A cool and more centralized way to handle labels would be to just use integers as labels for each Timelock object and then have only one Shared Object mapping integers to Strings. But maybe we don't need this complexity.

**Review by lzpap — DISMISSED** [review]
Looks amazing, thanks for the great effort with the tests! I don't think I've ever seen so detailed and thorough tests for any move package 🚀

**Review by lzpap — DISMISSED** [review]

**Review by miker83z — CHANGES_REQUESTED** [review]
LGTM! There's just a minor optimization regarding the `Label` drop that could be implemented!

**Review by miker83z — APPROVED** [review]

**Review by lzpap — APPROVED** [review]

**Pull request merged**
