### PR TITLE
feat(apps-ui-kit): add segmented button

### PR DESCRIPTION
**Pull request by brancoder**
# Description of change

Adds SegmentedButton component

## Links to any relevant issues

resolves #873 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by evavirseda — DISMISSED** [review]
nice job :rocket:

**Review by VmMad — CHANGES_REQUESTED** [review]
Minimal comment. Other than that I think it looks good

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by VmMad — CHANGES_REQUESTED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by panteleymonchuk — APPROVED** [review]
Tested locally, looks good.

**Review by marc2332 — APPROVED** [review]

**Review by evavirseda — APPROVED** [review]
:rocket:

**Review by VmMad — APPROVED** [review]

**Pull request merged**
