### PR TITLE
feat(wallet-dashboard): hook collect(unwrap) feature to dashboard

### PR DESCRIPTION
**Pull request by cpl121**
# Description of change

Hook collect(unwrap) feature to dashboard

## Links to any relevant issues

Closes #1087 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by brancoder — CHANGES_REQUESTED** [review]
looks good just need to polish the tx creation a bit

**Review by brancoder — DISMISSED** [review]
LG, collecting works just a comment on tx success and error handling improvements

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — COMMENTED** [review]
mini comment

**Review by marc2332 — CHANGES_REQUESTED** [review]
`all` seems redundant right?

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — DISMISSED** [review]

**Review by begonaalvarezd — APPROVED** [review]

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by brancoder — CHANGES_REQUESTED** [review]
LG just a small improvement

**Review by brancoder — APPROVED** [review]
LGTM :+1:

**Review by begonaalvarezd — APPROVED** [review]

**Review by brancoder — CHANGES_REQUESTED** [review]
the CI is failing :pray: 
name changes to `ExtendedDelegatedTimelockedStake` is causing vesting.spec tests to fail

**Review by brancoder — APPROVED** [review]
LGTM

**Pull request merged**
