### PR TITLE
feat(dashboard): add logic send coin popup

### PR DESCRIPTION
**Pull request by cpl121**
# Description of change

Add logic send coin popup

## Links to any relevant issues

fixes issue #284

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Send coin

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by marc2332 — CHANGES_REQUESTED** [review]
I know it's on draft but I thought some of these points are important

**Review by marc2332 — DISMISSED** [review]

**Review by brancoder — CHANGES_REQUESTED** [review]
resolve conflicts :pray:

**Review by brancoder — CHANGES_REQUESTED** [review]
resolve conflicts :pray:

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by evavirseda — CHANGES_REQUESTED** [review]

**Review by evavirseda — DISMISSED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — COMMENTED** [review]
great work 🚀 added 2 mini comments

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by marc2332 — DISMISSED** [review]
small details.

**Review by brancoder — DISMISSED** [review]
great work :+1:

**Review by brancoder — DISMISSED** [review]

**Review by msarcev — DISMISSED** [review]

**Review by brancoder — DISMISSED** [review]

**Review by evavirseda — APPROVED** [review]

**Review by brancoder — APPROVED** [review]

**Review by VmMad — APPROVED** [review]
lgtm

**Review by begonaalvarezd — APPROVED** [review]

**Pull request merged**
