### PR TITLE
feat: upgrade rust toolchain to 1.81

### PR DESCRIPTION
**Pull request by thibault-martinez**
Checking if everything goes well in the CI.
Does anything else need to be changed/tested?

### CODE REVIEW

**Review by Thoralf-M — APPROVED** [review]

**Review by valeriyr — APPROVED** [review]
LGTM!

**Review by piotrm50 — APPROVED** [review]

**Review by muXxer — APPROVED** [review]

**Review by muXxer — APPROVED** [review]

**Comment by muXxer** [comment]
Please also run `RUSTFLAGS="--cfg msim" cargo clippy --fix` to fix the clippy errors in the msim related code paths (this is not checked right now in the CI).

**Review by DaughterOfMars — APPROVED** [review]
Assuming this did not cause the e2e test to break

**Comment by thibault-martinez** [comment]
> Assuming this did not cause the e2e test to break

Pretty sure it's unrelated.

**Review by Alex6323 — APPROVED** [review]

**Pull request merged**
