### PR TITLE
feat(docs) : Add Network Overview Page

### PR DESCRIPTION
**Pull request by vivekjain23**
# Description of change

Added Network Overview Page to the docs.

## Links to any relevant issues

 fixes [#1614](https://github.com/iotaledger/iota/issues/1614).

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Built locally.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [X] I have followed the contribution guidelines for this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Thoralf-M — APPROVED** [review]

**Review by lucas-tortora — CHANGES_REQUESTED** [review]
Could you move this outside the Getting Started section? Something similar to https://wiki.iota.org/build/networks-endpoints/. As well, please add links to and from the [Connect to a network](https://iota3-wiki-86224a49db5aefb63c2cbbbbdfdecbc9e1e90732-dgro95h9s.vercel.app/developer/getting-started/connect#add-a-network-environment), and [Local development](https://iota3-wiki-86224a49db5aefb63c2cbbbbdfdecbc9e1e90732-dgro95h9s.vercel.app/developer/getting-started/local-network) sections

**Review by lucas-tortora — CHANGES_REQUESTED** [review]
Thanks for the updates :) It's looking good to me, but I think there's still some improvements we can make:
1. Could you add the network overview table in https://iota3-wiki-86224a49db5aefb63c2cbbbbdfdecbc9e1e90732-iatmrcpub.vercel.app/developer/
2. Please add the devnet and testnet to the constants file (we can use placeholders for now), as in https://github.com/iotaledger/iota-wiki/blob/main/src/theme/constant.tsx. This way, we can call it as in https://github.com/iotaledger/iota-wiki/blob/main/docs/build/getting-started/networks-endpoints.mdx?plain=1#L41 , and we only need to update network information in one file.

**Review by lucas-tortora — CHANGES_REQUESTED** [review]
Almost there :) Please add the devnet and testnet to the constants file (we can use placeholders for now), as in https://github.com/iotaledger/iota-wiki/blob/main/src/theme/constant.tsx. This way, we can call it as in https://github.com/iotaledger/iota-wiki/blob/main/docs/build/getting-started/networks-endpoints.mdx?plain=1#L41 , and we only need to update network information in one file.

**Review by lucas-tortora — CHANGES_REQUESTED** [review]

**Review by lucas-tortora — APPROVED** [review]

**Review by Ginowine — APPROVED** [review]
LGTM

**Pull request merged**
