### PR TITLE
feat(wallet): update styles for the Send Token page

### PR DESCRIPTION
**Pull request by VmMad**
# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

Fixes #1784 

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by evavirseda — CHANGES_REQUESTED** [review]
need a few more tweaks :pray:

**Review by evavirseda — APPROVED** [review]
:rocket:

**Review by begonaalvarezd — COMMENTED** [review]
tiny comment but the PR works great 🚀 amazing work

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Something is off with the amount validation, I cant send when before I could
before: no validation errors
image
image
in this PR: 
image
image

Additionally, before the amount reset everytime the selected coin changed, we could keep it that way

**Review by brancoder — CHANGES_REQUESTED** [review]
After changing the Autolock select option  the Save button is disabled.
To reproduce click the checkbox and input some value in the input and than change the select option from hours to minutes:
image

**Review by cpl121 — CHANGES_REQUESTED** [review]
I can't send a custom amount
Captura de pantalla de 2024-09-04 10-02-44

It only works if I put everything
Captura de pantalla de 2024-09-04 10-03-07

**Review by brancoder — CHANGES_REQUESTED** [review]
Fix Select storybook and also im experiencing some issues with amount validation in send flow
image

**Review by brancoder — APPROVED** [review]
LGTM :confetti_ball:

**Review by evavirseda — CHANGES_REQUESTED** [review]
everything works really great, nice job jean :100: 
but t needs a little more love :female_detective:  :pray: 
Screenshot from 2024-09-04 18-42-19
Screenshot from 2024-09-04 18-42-52

**Review by evavirseda — APPROVED** [review]
looks great, we can polish the small details later :rocket: :moon:

**Review by cpl121 — APPROVED** [review]

**Review by begonaalvarezd — APPROVED** [review]

**Pull request merged**
