### PR TITLE
task(devx): Update TS SDK docs

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

* replaced `signTransactionBlock` with `signTransaction` in examples
* replaced `signAndExecuteTransactionBlock` with `signAndExecuteTransaction` in examples
* replaced `fromHEX with `fromHex` in examples
* replaced `toHEX with `toHex` in examples
* replaced `TransactionBlock` with `Transaction` in examples
* replaced `tx` with `txb` in examples
* replaced `fromB64` with `fromBase64` in examples
* removed refs to deprecated methods that were delted in https://github.com/iotaledger/iota/pull/3560/
* updated bcs examples
* added useReportTransactionEffects doc
* added useSignAndExecuteTransaction doc
* added useSignTransaction doc
* deleted useSignTransactionBlock doc
* deleted useSignAndExecuteTransactionBlock doc
* replaced `requiredFeatures` with `walletFilters` in wallet-provider.mdx
* added `fromSecretKey` example to keypairs.mdx
* added doc for Transaction Executors
* added doc for Transaction Plugins
* added doc for GraphQL
* added rate limit warning in faucet.mdx
* removed the deprecated classes section in ts sdk index
* removed fromV1 guide for the Kiosk

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/3800

## Type of change

- Documentation Fix

## How the change has been tested

Docs were built locally.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Ginowine — APPROVED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]
Some parts of the docs seem to be formatted with tabs  and other with spaces, can you format everything with spaces? 🙏🏻

**Review by salaheldinsoliman — APPROVED** [review]
Looks great, just a few suggestions

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by vivekjain23 — CHANGES_REQUESTED** [review]

**Review by vivekjain23 — APPROVED** [review]
Minor changes are required.

**Review by marc2332 — APPROVED** [review]
lgtm for me, just needs to fix what was requested above 👆🏻

**Pull request merged**
