### PR TITLE
refactor(iota-node): Simplify shutdown logic

### PR DESCRIPTION
**Pull request by sergiupopescu199**
# Description of change
- Removed the use of `tokio::sync::broadcast` channel to send a shutdown signal and replaced with the `CancellationToken`
- in `wait_termination()` removed the use of `.boxed()` on futures as it only added additional heap allocation.

## Links to any relevant issues
fixes issue #1190 

## Type of change

Choose a type of change, and delete any options that are not relevant.
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

 builds locally using this command
```bash
RUST_LOG=info cargo r --bin iota-node -- --config-path $HOME/.iota/iota_config/fullnode.yaml
```
- For simulating the sending of the shutdown message I modified locally the [pub async fn monitor_reconfiguration(self: Arc<Self>) -> Result<()>](https://github.com/iotaledger/iota/blob/develop/crates/iota-node/src/lib.rs#L1511) by commenting this lines
```rust
// let stop_condition = checkpoint_executor
//     .run_epoch(cur_epoch_store.clone(), run_with_range)
//     .await;
```
and adding this one, by forcing the `stop_condition` to always resolve to the `RunWithRangeCondition` enum variant
```rust
let stop_condition = StopReason::RunWithRangeCondition;
```
in this way [`the condition`](https://github.com/iotaledger/iota/blob/develop/crates/iota-node/src/lib.rs#L1515) will always be true and the node will shutdown automatically. 

Also in `wait_termination()` added a log to catch if the `shutdown_signal` branch will run
```rust
tokio::select! {
    _ = sigint => {},
    _ = sigterm_recv => {},
    _ = shutdown_signal.cancelled() => {
        println!("Shutdown Signal Received");
    },
}
```

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.
- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by Thoralf-M — APPROVED** [review]

**Review by PhilippGackstatter — APPROVED** [review]
Nice improvement!

**Review by kodemartin — APPROVED** [review]
:lgtm: nice @sergiupopescu199

**Review by kodemartin — CHANGES_REQUESTED** [review]
halting to review the implications on `iota-test-e2e`

https://github.com/iotaledger/iota/pull/1304#issuecomment-2245123421

It might be the case that tests wait forever for a shutdown. Could you check this out @sergiupopescu199 ? That is, if there are tests that actually expect a shutdown signal from the broadcast channel.

**Review by kodemartin — COMMENTED** [review]
I am afraid that this refactoring is not that simple afterall. It seems to affect the design of the node configuration, and in specific this particular feature:

https://github.com/iotaledger/iota/blob/b478e86c4d13e5b975fcef54a69c6d66c6f18560/crates/iota-config/src/node.rs#L1081-L1088

The shutdown logic as it were is closely related to this as far as I understand.

I would therefore suggest to stall this and let the node team revisit this potential improvement.

What do you think @PhilippGackstatter, @sergiupopescu199 ?

**Pull request closed without merging**
