### PR TITLE
feat(wallet): Rebrand manage accounts

### PR DESCRIPTION
**Pull request by panteleymonchuk**
Closes #1782

### CODE REVIEW

**Review by VmMad — CHANGES_REQUESTED** [review]

**Review by evavirseda — CHANGES_REQUESTED** [review]
need some updates :pray:

**Review by evavirseda — CHANGES_REQUESTED** [review]
just one detail :pray:

**Review by evavirseda — CHANGES_REQUESTED** [review]
:pray:

**Review by cpl121 — APPROVED** [review]
Nice job! 👏🏼

**Review by brancoder — DISMISSED** [review]
conflicts :pray:

**Review by marc2332 — CHANGES_REQUESTED** [review]
👋🏻

**Review by evavirseda — APPROVED** [review]
nice job :rocket: :moon:

**Review by marc2332 — APPROVED** [review]

**Review by VmMad — CHANGES_REQUESTED** [review]
Looking good. Just a few changes

**Review by VmMad — APPROVED** [review]

**Pull request merged**
