### PR TITLE
feat(wallet): polish overlay for connect dapp

### PR DESCRIPTION
**Pull request by panteleymonchuk**
Closes #2374

### CODE REVIEW

**Review by evavirseda — DISMISSED** [review]
I think the best way to fix this is by increasing the `popup-height` tailwind variable to `710px` :bulb:  without the `max-h-popup-height` class, the extension doesn’t display right when opened in a new browser tab, like this :see_no_evil: 
image

**Review by marc2332 — COMMENTED** [review]
Not a fan of this as it introduces a double render, I am neither approving nor requesting changes.

**Review by brancoder — CHANGES_REQUESTED** [review]
After discussion we decided to revert the solution and opt for this proposal
https://github.com/iotaledger/iota/pull/2776#pullrequestreview-2318624215

**Review by brancoder — APPROVED** [review]
LGTM :+1:

**Review by begonaalvarezd — APPROVED** [review]

**Pull request merged**
