### PR TITLE
feat(apps-ui-kit): add custom tailwind palettes

### PR DESCRIPTION
**Pull request by VmMad**
# Description of change

Adds the necessary palettes and custom classes to tailwind config.

## Links to any relevant issues

Fixes #950 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by brancoder — CHANGES_REQUESTED** [review]
Also the complete error 'red' pallet needs to be updated to the latest changes

**Review by brancoder — CHANGES_REQUESTED** [review]
Also the rest of the neutral panel colors need to be updated

**Review by brancoder — DISMISSED** [review]
LGTM

**Review by evavirseda — CHANGES_REQUESTED** [review]
looks great, but CI is failing :pray:

**Review by evavirseda — DISMISSED** [review]

**Review by brancoder — COMMENTED** [review]
Do we have to add remaining colors from palettes like Shader/Neutral

**Review by evavirseda — DISMISSED** [review]

**Review by brancoder — APPROVED** [review]
LGTM :confetti_ball:

**Review by evavirseda — APPROVED** [review]

**Pull request merged**
