### PR TITLE
feat(iota-genesis-builder): Generate test data only object snapshot

### PR DESCRIPTION
**Pull request by miker83z**
# Description of change

Creates an example that takes a Hornet snapshot in input, empties it and then fills it with test outputs plus some outputs dedicated to a delegator.

The delegator address is the same used in the genesis-builder. The delegator will have 100 gas coins with 1 million IOTA balance each and 100 timelocked coins with 1 million IOTA balance each.

- Generated object snapshot -> 9.8 MB
- Generated genesis.blob -> 4.3 MB

## Links to any relevant issues

Fixes #1170 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested
In order:
- `cargo run --release --example snapshot_only_test_outputs --features="test-outputs" ../latest-full_snapshot-iota.bin`
- `cargo run --release --bin iota-genesis-builder -- --disable-global-snapshot-verification iota --snapshot-path ../test-latest-full_snapshot-iota.bin --target-network alphanetv0`
- `cargo run --release --example build_stardust_genesis`

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by kodemartin — APPROVED** [review]
Hey @miker83z, looks good! Left some minor suggestions.

I tested it by running `iota-test-validator` with 4 validators successfully, so this can close #963 as well.

> [!NOTE]
> The test data does not reproduce #1168 though.

**Review by kodemartin — CHANGES_REQUESTED** [review]
> Hey @miker83z, looks good! Left some minor suggestions.
> 
> I tested it by running `iota-test-validator` with 4 validators successfully, so this can close #963 as well.
> 
> Note
> 
> The test data does not reproduce #1168 though

On second thought, this implies that the test data do not represent completely the possible realizations of the original stardust ledger. That is, the reason that #1168 is not reproduced is because no foundry, or output with native tokens is included. 

Therefore I think we should aim at first sampling completely all the original UTXOs, and then add the new ones. Otherwise we limit a lot the possible failures.

**Review by kodemartin — COMMENTED** [review]
> > > Hey @miker83z, looks good! Left some minor suggestions.
> > > I tested it by running `iota-test-validator` with 4 validators successfully, so this can close #963 as well.
> > > Note
> > > The test data does not reproduce #1168 though
> > 
> > 
> > On second thought, this implies that the test data do not represent completely the possible realizations of the original stardust ledger. That is, the reason that #1168 is not reproduced is because no foundry, or output with native tokens is included.
> > Therefore I think we should aim at first sampling completely all the original UTXOs, and then add the new ones. Otherwise we limit a lot the possible failures.
> 
> Added with [c610f64](https://github.com/iotaledger/iota/pull/1182/commits/c610f640b8fb4dca6b31c357ac6dd3b48611bd01), even though it doesn't seem to affect the results. Indeed, foundries and output with native tokens were already included before with `alias_ownership::outputs()` and `stardust_mix::outputs()`.

Since we saw in #1168 that the lack of sampling was not an issue, I think we can opt out of sampling the original snapshot after all. The main concern with any sampling does not take account of the relations between the outputs is that it might lead to dangling object relations in the migrated state. Which would probably cause the migration to fail.

There is nevertheless merit in making the test data as representative as possible to the original ledger. A few first steps towards this direction are the following:

* Make the test-output generation idempotent by fixing the seed for the random number generators used.
* Ensure that we have at least one object for each output kind.
* Ensure that we have at least one object relation between any pair of relatable output kinds.

The last couple of requirements might be already satisfied, but it is worthwhile revisiting random generations that allow no value to be generated.

This can be treated in a different issue though.

If the need for more elaborate sampling of the original ledger arises then we can handle it in the future.

**Review by kodemartin — DISMISSED** [review]
lgtm, subject to resolving [this outstanding comment](https://github.com/iotaledger/iota/pull/1182#issuecomment-2238861849). 

It could be treated in a separate PR though.

**Review by Thoralf-M — DISMISSED** [review]

**Review by lzpap — DISMISSED** [review]

**Review by Dkwcs — DISMISSED** [review]

**Review by Thoralf-M — DISMISSED** [review]

**Review by kodemartin — DISMISSED** [review]

**Review by kodemartin — APPROVED** [review]

**Review by lzpap — APPROVED** [review]

**Pull request merged**
