### PR TITLE
feat(explorer): Improve Collapsible components

### PR DESCRIPTION
**Pull request by panteleymonchuk**
Closes #2883

### CODE REVIEW

**Review by marc2332 — APPROVED** [review]
<details>
  <summary>click to here see my thoughts</summary>
  
image

</details>

**Review by brancoder — CHANGES_REQUESTED** [review]
LGTM just a nit: we should add some padding between owned coins
image

**Review by evavirseda — CHANGES_REQUESTED** [review]
nice job, just one detail :pray:

**Review by brancoder — APPROVED** [review]
LGTM

**Review by evavirseda — APPROVED** [review]
:rocket:

**Pull request merged**
