### PR TITLE
feat(wallet-dashboard): add logic to activity detail popup

### PR DESCRIPTION
**Pull request by VmMad**
# Description of change

Adds logic to activity detail popup 

## Links to any relevant issues

Fixes #301 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by marc2332 — APPROVED** [review]
not approving, just testing

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by cpl121 — CHANGES_REQUESTED** [review]
conflicts 🙏🏼

**Review by cpl121 — CHANGES_REQUESTED** [review]
bad imports

**Review by cpl121 — CHANGES_REQUESTED** [review]

**Review by brancoder — CHANGES_REQUESTED** [review]
conflicts :pray:

**Review by msarcev — DISMISSED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by brancoder — DISMISSED** [review]
conflicts @VmMad  :pray:

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by msarcev — DISMISSED** [review]

**Review by cpl121 — CHANGES_REQUESTED** [review]
conflicts 🙏🏼

**Review by msarcev — DISMISSED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — APPROVED** [review]

**Review by cpl121 — APPROVED** [review]

**Pull request merged**
