### PR TITLE
refactor(devx): Docs - Refactor Top Level Navigation

### LINKED ISSUE #4047: Restructure the wiki and plan content to ensure navigation is intuitive
As there will be a huge load of changes in Wiki, we should ensure that the navigation is intuitive. At the moment, this means splitting the content into 3 main sections:

- **Learn** about the protocol and ecosystem.
- **Build** on the protocol.
- **Maintain** the network infrastructure by running your own node

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

Refactored the docs to accommodate the discussed top-level navigation:

* **About IOTA**: Information about the protocol, wallets, etc. Used to be the `Concepts` section.
  * This section has been slimmed down considerably, as both the `App Developers` and `Cryptography` sections have been merged with `Developers > IOTA 101` and `Developers > Cryptography`, respectively.
* **Developers**: Guides and explanations to build on IOTA. Used to be the `Guides` section.
  * The biggest change to this section has been separating its content between `Developers` and `Node Operators`.
  * The `Standards` section has been moved into this section.
  * Other changes include merging the `Cryptography` and `App Developers` sections (as mentioned above), and including the `First dApp` guide in `Getting Started`.
* **Node Operators**:  Guides on operating an IOTA node. This is a new section, which basically includes what used to be `Guides > Operator`.
* **References**: Self-explantory.
* **Integrate your exchange**: Temporary link for external partners.

## Notes to Reviewers

Changing the top-level navigation and migrating content between sections will inevitably result in a huge PR. However, this PR does not change any content (i.e., text) other than links that need to be updated.  So please focus on information architecture and intuitive navigation of the documentation. 

Content edits will be addressed by section in subsequent PRs that will apply the [Diataxis](https://diataxis.fr/) framework to the current content and later add and edit content per section, 

## Links to any relevant issues

fixes https://github.com/iotaledger/iota/issues/4047

## Type of change

- Documentation Refactor

## How the change has been tested

Wiki was built locally.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Dr-Electron — COMMENTED** [review]
Do we really need `Integrate Your Exchange` as top level Navbar item?

**Review by Dr-Electron — DISMISSED** [review]
I like the Navbar change. Separates the topics clearly by user type. The Dev section got a little worse, but that is something we have to cleanup with diataxis. Tbf I think even in the original docs it was bad 😆

**Review by Dr-Electron — DISMISSED** [review]

**Review by jlvandenhout — COMMENTED** [review]
Overall, with the new content layout and the new styling, this looks really awesome!

**Review by Dr-Electron — APPROVED** [review]

**Review by salaheldinsoliman — APPROVED** [review]
The navigation looks quite intuitive
One question though: Why does the `Why Move` section belong to `Developers` section rather than `About IOTA`?
`Why Move` seems to explain some information that integrates well right after explaining `Understand IOTA Security`

WDYT?

**Pull request merged**
