### PR TITLE
Added a Stardust system package with basic unlock conditions implementation

### PR DESCRIPTION
**Pull request by valeriyr**
# Description of change

This PR introduces a new system package that is called `Stardust`. 

The package contains modules that are related to:
- Unlock conditions

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Will be done with NFTs implementation.

### CODE REVIEW

**Review by fijter — APPROVED** [review]
Nicely designed and well structured, very nice!

**Review by miker83z — APPROVED** [review]
LGTM!

**Review by lzpap — APPROVED** [review]
@valeriyr Fix the `drop` abilities and the getters and will be good to go

**Review by lzpap — APPROVED** [review]
🚀

**Pull request merged**
