### PR TITLE
chore(tooling): remove old frens and domains mentions

### PR DESCRIPTION
**Pull request by panteleymonchuk**
Closes #1593
Depends on: https://github.com/iotaledger/iota/pull/3172

### CODE REVIEW

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Found other mentions we should remove  
- https://github.com/iotaledger/iota/blob/fd5009615bd27f63676e829cdea0b356bc3df69e/dapps/kiosk-cli/index.js#L140
- https://github.com/iotaledger/iota/blob/fd5009615bd27f63676e829cdea0b356bc3df69e/dapps/kiosk-cli/index.js#L146
- https://github.com/iotaledger/iota/blob/fd5009615bd27f63676e829cdea0b356bc3df69e/sdk/kiosk/src/client/kiosk-transaction.ts#L156

Additionally, alongside the removal of iotafrens the whole capybara thing should also be removed, therefore imo the tests here https://github.com/iotaledger/iota/blob/b4daae6303f9a18249e2dfbaaedf560376c27eee/sdk/typescript/src/transactions/__tests__/bcs.test.ts should be adapted so that it does not use `Capy` but something else. If this last part is too much for this PR please notify @begonaalvarezd to track it in a separate issue

**Review by begonaalvarezd — APPROVED** [review]

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Found some mentions to bullshark in 
- `apps/wallet/src/ui/app/pages/home/interstitial/index.tsx`
- `apps/wallet/src/ui/app/components/iota-apps/Banner.tsx`
- `apps/wallet/src/shared/analytics/ampli/index.ts`

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by evavirseda — CHANGES_REQUESTED** [review]
:pray:

**Review by evavirseda — APPROVED** [review]

**Review by begonaalvarezd — APPROVED** [review]
🕺🏼

**Review by marc2332 — APPROVED** [review]

**Pull request merged**
