### PR TITLE
feat(tooling-explorer): Rebrand homepage navbar

### PR DESCRIPTION
**Pull request by msarcev**
# Description of change

Rebrand homepage navbar

## Links to any relevant issues

Closes https://github.com/iotaledger/iota/issues/1875

### CODE REVIEW

**Review by brancoder — DISMISSED** [review]
LG just couple of minor commnets

**Review by brancoder — COMMENTED** [review]
LGTM and its by the Figma but actually the search bar looks better when its larger, because you can see all of the info like the suggestion type.  wdyt?
image

**Review by brancoder — APPROVED** [review]
LGTM :confetti_ball:

**Review by evavirseda — DISMISSED** [review]
css police is back :pray: :innocent:

**Review by evavirseda — APPROVED** [review]
:rocket:

**Pull request merged**
