### PR TITLE
chore(core-node)!: Cleanup Narwhal related fields in IOTA Framework codebase (Move and Rust)

### PR DESCRIPTION
**Pull request by hmoog**
# Description of change

Cleanup of Narwhal related fields in IOTA Framework. We removed the `worker_address` field as it's no longer used in Mysticeti, and cleaned up naming of `protocol_key` -> `authority_key`, `worker_key` -> `protocol_key` across the codebase to be consistent with the naming in the consensus crate. This is to avoid confusion about keys being named differently in different components, especially if one name overlaps (i.e. different keys named `protocol_key` in the framework and the consensus).

This PR breaks GraphQL tests and potentially others related to APIs, but those further fixes should be addressed in separate PRs as we want to merge protocol breaking changes to start the testing phase ASAP.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/3145

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by miker83z — COMMENTED** [review]
Looks good! 
I mostly checked:
- iota-framework
- iota-genesis-builder
- iota-types
- iota (cli)

**Review by hmoog — COMMENTED** [review]
We should change / discuss these tmrw

**Review by lucas-tortora — APPROVED** [review]

**Review by alexsporn — APPROVED** [review]

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]

**Review by begonaalvarezd — APPROVED** [review]

**Review by junwei0117 — APPROVED** [review]
LGTM👍

**Review by miker83z — APPROVED** [review]

**Review by kodemartin — APPROVED** [review]

**Review by piotrm50 — APPROVED** [review]

**Review by Thoralf-M — APPROVED** [review]

**Review by miker83z — DISMISSED** [review]
`iota move test` is currently not working:
```
public native fun validate_metadata_bcs(metadata: vector<u8>);
│     │                       ^^^^^^^^^^^^^^^^^^^^^
│     │                       │
│     │                       INTERNAL TEST ERROR: Unexpected Deserialization Error
│ Test was not expected to error, but it gave a MALFORMED (code 3001) error originating in the module iota_system::validator rooted here
│     │                       In this function in iota_system::validator
```

**Review by miker83z — APPROVED** [review]

**Pull request merged**
