### PR TITLE
feat(tooling-sdk): Regenerate open-rpc graphql schema types

### PR DESCRIPTION
**Pull request by msarcev**
# Description of change

Steps taken:
* Regenerate iota-open-rpc spec with `cargo run --package iota-open-rpc --example generate-json-rpc-spec` **(It's actually the last commit cause it got lost in a rebase, but it was done first originally🤦🏻 )**
* Run generate script in sdk/typescript (`npx tsx scripts/generate.ts`)
* Fix TS-sdk build (updates `src/transactions/TransactionBlock.ts`)
* Add `iota_total_supply` method in `crates/iota-graphql-rpc/src/types/system_state_summary.rs` (otherwise on the TS side we cannot fix the build cause of missing field on SystemSummary)
* Run generate graphql-rpc schema command (`cargo run --package iota-graphql-rpc generate-schema --file ./crates/iota-graphql-rpc/schema/current_progress_schema.graphql`)
* Manually fix fields in getLatestIotaSystemState. Fix broken field name for `stakingPoolMappingsSize`, remove "stakeSubsidy" fields and add `iotaTotalSupply`. (Otherwise the `pnpm run codegen` fails)
* Re-generate `graphql-transport/src/generated/queries.ts` with `pnpm run codegen`
* Fix the field mappings in `graphql-transport/src/methods.ts`

Superseeds https://github.com/iotaledger/iota/pull/1126 !

## Links to any relevant issues

Based on branch https://github.com/iotaledger/iota/pull/1186
Closes https://github.com/iotaledger/iota/issues/1080

## Type of change

- Enhancement (a non-breaking change which adds functionality)

### CODE REVIEW

**Review by marc2332 — CHANGES_REQUESTED** [review]
shouldn't this also update `tada-env.ts`?

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by kodemartin — APPROVED** [review]
lgtm :cherry_blossom:

**Review by marc2332 — APPROVED** [review]
legend 👍🏻

**Review by Thoralf-M — APPROVED** [review]

**Review by begonaalvarezd — APPROVED** [review]
🌟

**Pull request merged**
