### PR TITLE
doc(node): Add execution related code docs

### PR DESCRIPTION
**Pull request by bingyanglin**
# Description of change

* Added doc comments to Move VM adapter code

## Links to any relevant issues

Close #1642

## Type of change

- Documentation Fix

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code

### CODE REVIEW

**Review by semenov-vladyslav — COMMENTED** [review]
A few doc comments need clarifications. Plus `ProgrammableTransaction` related function comments need the same unified phrasing.

**Review by semenov-vladyslav — CHANGES_REQUESTED** [review]
A few broken comments need to be fixed.

**Review by miker83z — CHANGES_REQUESTED** [review]
Looks good in general, some suggestions:

**Review by semenov-vladyslav — APPROVED** [review]
Looks good

**Review by jkrvivian — CHANGES_REQUESTED** [review]

**Review by miker83z — APPROVED** [review]

**Review by jkrvivian — APPROVED** [review]

**Pull request merged**
