### PR TITLE
refactor: Remove move object `has_public_transfer`

### PR DESCRIPTION
**Pull request by jkrvivian**
# Description of change

`has_public_transfer` is no longer used to determine whether a transaction can transfer this object. Instead, it is always calculated from the objects type when loaded in execution. So we remove it in this PR.

It's based on the removal of `has_publich_transfer` in iota-rust-sdk as well, here's the PR: https://github.com/iotaledger/iota-rust-sdk/pull/18

## Links to any relevant issues

#2092 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement

## Change checklist

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by muXxer — APPROVED** [review]

**Review by alexsporn — COMMENTED** [review]
@valeriyr can you please take a close look at this since this flag is explicitly marked with safety comments.

Is this really not required by the public API users?

**Review by miker83z — DISMISSED** [review]

**Review by kodemartin — CHANGES_REQUESTED** [review]
@jkrvivian there are few additional changes need w.r.t. `iota-graphql-e2e-tests`, and `iota-graphql-rpc`. 

Please see [this guide](https://iotafoundation.atlassian.net/wiki/spaces/IF/pages/2288615541/Updates+on+Public+API+GraphQL+JSON+RPC+and+Typescript+SDK) for more information.

**Review by miker83z — CHANGES_REQUESTED** [review]
Looks good (not considering CI)! 

Pls check all the `unsafe` modifiers in the functions that call `new_from_execution_with_limit`, these should be removed.

**Review by kodemartin — APPROVED** [review]

**Review by miker83z — APPROVED** [review]
Looks good! Just the tests to fix

**Review by lucas-tortora — APPROVED** [review]

**Review by begonaalvarezd — APPROVED** [review]

**Review by valeriyr — CHANGES_REQUESTED** [review]
Looks good :+1: a lot of work has been done :muscle:

**Review by valeriyr — APPROVED** [review]
Looks good, thank you!

**Review by thibault-martinez — APPROVED** [review]

**Pull request merged**
