### PR TITLE
feat(iota-genesis-builder): add compression flag to Stardust Objects Snapshot creation

### PR DESCRIPTION
**Pull request by miker83z**
# Description of change

This PR adds a compression and decompression flags to Stardust Objects Snapshot creation and reading. The default is **false**.

## Links to any relevant issues

Fixes #862  

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

- `cargo run --release --bin iota-genesis-builder iota --snapshot-path ../latest-full_snapshot-iota.bin --target-network alphanetv0`
- `cargo run --release --bin iota-genesis-builder -- --compress iota --snapshot-path ../latest-full_snapshot-iota.bin --target-network alphanetv0`
- `cargo run --release --example build_stardust_genesis`
- `cargo run --release --example build_stardust_genesis -- -d`

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by kodemartin — CHANGES_REQUESTED** [review]
Looks good on the application side. I left a comment to raise the level of the `compress` option.

You have to handle decompression as well. Check out also #862 

For #863 I would suggest making a dedicated PR.

**Review by samuel-rufi — COMMENTED** [review]
Looks good @miker83z ! Basically just what @kodemartin mentioned.

**Review by kodemartin — APPROVED** [review]
lgtm

**Review by samuel-rufi — APPROVED** [review]
Looks great @miker83z !

**Pull request merged**
