### PR TITLE
feat(wallet): rebrand balance section

### PR DESCRIPTION
**Pull request by panteleymonchuk**
# Description of change

image

## Links to any relevant issues

Close #1766 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by begonaalvarezd — COMMENTED** [review]
Really nice 💪🏼 added some comments but this looks great

**Review by evavirseda — CHANGES_REQUESTED** [review]
nice job! added some comments!

**Review by evavirseda — CHANGES_REQUESTED** [review]
just one detail!

**Review by VmMad — CHANGES_REQUESTED** [review]
Rest looks good I think

**Review by VmMad — APPROVED** [review]
lgtm

**Review by evavirseda — APPROVED** [review]
nice job :rocket:

**Pull request merged**
