### PR TITLE
refactor(iota-indexer): Do not panic on errors in iota_indexer::framework::runner::run

### PR DESCRIPTION
**Pull request by tomxey**
# Description of change

Refactored iota_indexer::framework::runner::run to return the errors from handlers instead of panicking, motivated by #1569. Refactored the function to reduce code duplication.

## Links to any relevant issues

fix #1569

## Type of change

- Refactor

## How the change has been tested

- cargo test
- ran the indexer locally and observed that checkpoints are synced without errors

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by sergiupopescu199 — COMMENTED** [review]
I've spotted an `unwrap` in the `run` function

https://github.com/iotaledger/iota/blob/5ea37775e44f26ce4b6e35d62f197a15b4265b4c/crates/iota-indexer/src/framework/runner.rs#L31

**Review by samuel-rufi — COMMENTED** [review]
Looks good! Only minor suggestion to fix `rustfmt` and the typo you mentioned above.

**Review by samuel-rufi — APPROVED** [review]

**Review by samuel-rufi — CHANGES_REQUESTED** [review]
Seems like clippy is failing the CI check

**Review by kodemartin — CHANGES_REQUESTED** [review]
Hey @tomxey looks good. Let just a few suggestions to improve the patch.

Plus, mind `clippy`.

**Review by kodemartin — APPROVED** [review]
lgtm :polar_bear:

**Review by samuel-rufi — APPROVED** [review]

**Pull request merged**
