### PR TITLE
feat(iota-json-rpc-api): Restore explorer metric endpoints

### PR DESCRIPTION
**Pull request by samuel-rufi**
# Description of change

Restores the explorer metric endpoints.

## Links to any relevant issues

Fixes https://github.com/iotaledger/iota/issues/1619

## Dependencies

- https://github.com/iotaledger/iota/issues/1848

## How the change has been tested

- I have run the `docker-compose` setup and tested the RPC endpoints with `curl`.

Try it yourself:

```bash
cd docker/pg-services-local
docker compose build
docker compose up -d
```

```bash
curl -s localhost:9005 --header 'Content-Type: application/json' --data '{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "iotax_getEpochMetrics",
  "params": []
}' | json_pp
```

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by kodemartin — CHANGES_REQUESTED** [review]
Good job @samuel-rufi! Left a few comments and suggestions of non-critical nature nevertheless.

**Review by kodemartin — APPROVED** [review]
lgtm :cherry_blossom:

**Review by sergiupopescu199 — APPROVED** [review]
lgtm 🚀

**Review by Thoralf-M — APPROVED** [review]

**Review by tomxey — APPROVED** [review]
lgtm

**Pull request merged**
