### PR TITLE
feat(wallet-dashboard): add activity list logic.

### PR DESCRIPTION
**Pull request by panteleymonchuk**
# Description of change

Show activities list for wallet.

## Links to any relevant issues

Fixes #299

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

1. Make some transactions.
2. Connect wallet.
3. Go to "Activity" page. And make sure that transactions there.

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by evavirseda — CHANGES_REQUESTED** [review]
:pray:

**Review by VmMad — CHANGES_REQUESTED** [review]
Some function renaming for better clarity

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by cpl121 — CHANGES_REQUESTED** [review]
There is an error when opening the activity details popup since `timestamp` can be `undefined`

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by cpl121 — CHANGES_REQUESTED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by VmMad — DISMISSED** [review]

**Review by cpl121 — CHANGES_REQUESTED** [review]
we are so close! 🤞🏼

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by brancoder — DISMISSED** [review]
Rename changes :pray:

**Review by cpl121 — DISMISSED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by cpl121 — DISMISSED** [review]

**Review by evavirseda — DISMISSED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by marc2332 — CHANGES_REQUESTED** [review]

**Review by evavirseda — APPROVED** [review]
:rocket:

**Review by marc2332 — APPROVED** [review]

**Review by cpl121 — APPROVED** [review]

**Pull request merged**
