### PR TITLE
feat(iota-genesis-builder): Add delegate genesis stake logic

### PR DESCRIPTION
**Pull request by miker83z**
# Description of change

Creates a new logic for handling genesis Delegate stake and in particular Timelock delegation. 

## Issues

Fixes #703
Fixes #705

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

`cargo run --release --example build_stardust_genesis`

### CODE REVIEW

**Review by kodemartin — COMMENTED** [review]
Here are my first remarks:

* The logic seems to be correct
* We can deal with the remainder of gas-coins by adding a new `TokenAllocation` with no stake directly during delegation
* The gas-coins burning can be done by evicting them from the `objects` created in L274. 
* The loop implementation can be simplified by using iterators
* The derivative total amounts in `GenesisStake` can be added as methods, to simplify the struct, and reduce the side-effects in `delegate_genesis_stake`.

**Review by kodemartin — COMMENTED** [review]
> @kodemartin added [a367bf2](https://github.com/iotaledger/iota/pull/741/commits/a367bf20a228a0d59bd51540cd4387f828d0b020) to make it build! (so the build fully works now 🎉 )

Great! Added some minor suggestions on these changes.

> The commit also adds the genesis_stake generation as a required step during the Builder instantiation (check the example) so that since the start we know if it is a vanilla or not. This is also needed by the validation.

> Finally, I would wait for https://github.com/iotaledger/iota/pull/812 to be merged in order to modify the commands for the TimeLock PTB (current version works, but with the new TimeLock interface is less dirty, i.e., we don't need a special execution environment).

:+1:

**Review by kodemartin — APPROVED** [review]

**Review by DaughterOfMars — CHANGES_REQUESTED** [review]
Lots of CI is failing that should not be

**Review by samuel-rufi — APPROVED** [review]

**Review by PhilippGackstatter — COMMENTED** [review]
Preliminary comments.

**Review by PhilippGackstatter — APPROVED** [review]
Looks solid to me, nice work!

Just some constructive feedback: I think this PR would've benefitted from a more extensive PR description that went over the high level approach for the solution and which problem it is solving (briefly restated). That would've helped me review it more quickly and easily, since it is doing non-trivial things, but that might just be my preference.

**Pull request merged**
