### PR TITLE
feat(wallet): rebrand approve connection.

### PR DESCRIPTION
**Pull request by panteleymonchuk**
Closes #2088

Depends on https://github.com/iotaledger/iota/pull/2094

### CODE REVIEW

**Review by evavirseda — CHANGES_REQUESTED** [review]
need to update some styles :pray:  and I also think we should indicate when an account is selected and not show the three dots on hover (as shown in the screenshot video)
[Tooling – Figma.webm](https://github.com/user-attachments/assets/fefae3b6-656f-4214-ae4f-9ed6e15a35e7)

**Review by evavirseda — CHANGES_REQUESTED** [review]
I think you might want to explicitly opt in to the pre-commit hooks in your setup :bulb: :pray:

**Review by evavirseda — APPROVED** [review]
:rocket:

**Review by brancoder — CHANGES_REQUESTED** [review]
LG just a few minor comments

**Review by brancoder — APPROVED** [review]
LGTM :confetti_ball:

**Review by brancoder — CHANGES_REQUESTED** [review]
Build is failing :pray:

**Review by brancoder — APPROVED** [review]
LGTM

**Pull request merged**
