### PR TITLE
feat(docs): Architecture/flow diagrams implementation for iota_execution

### PR DESCRIPTION
**Pull request by Dkwcs**
# Description of change

Up-to-date docs of iota-execution crate with visual flow diagrams.
Flow/architecture diagrams have added for iota_execution crate in order to have general view of component interaction. It includes visual/textual description of iota_execution crate and also its subcrates(iota_adapter, iota_move_natives), sequence of transaction flow.

## Type of change

- Documentation  enhancement

### CODE REVIEW

**Review by miker83z — CHANGES_REQUESTED** [review]
Good addition to the docs! Some changes to make it clearer:

**Review by miker83z — CHANGES_REQUESTED** [review]

**Review by Dr-Electron — COMMENTED** [review]
Just a quick comment: If we use drawio for this diagrams, I would make the images svgs with the metadata integrated, instead of splitting it into two files

**Review by miker83z — DISMISSED** [review]

**Review by miker83z — DISMISSED** [review]

**Review by fijter — DISMISSED** [review]
Thanks! It probably needs a reference to these pages somewhere in the sidebar, but we can take care of that later/seperate too.

**Review by lzpap — APPROVED** [review]

**Review by valeriyr — APPROVED** [review]
Looks great @Dkwcs!

**Review by lucas-tortora — APPROVED** [review]

**Review by miker83z — APPROVED** [review]

**Pull request merged**
