### PR TITLE
feat(apps-ui-kit): add chip component

### PR DESCRIPTION
**Pull request by VmMad**
# Description of change

Adds chip component. 

## Links to any relevant issues

Fixes #881 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by brancoder — CHANGES_REQUESTED** [review]
conflicts  :pray:

**Review by evavirseda — CHANGES_REQUESTED** [review]

**Review by evavirseda — APPROVED** [review]
nice job :rocket:

**Review by evavirseda — CHANGES_REQUESTED** [review]
sorry 🙏, this is unnecessary now :see_no_evil:  you can import from the `ui-icons` library.

**Review by evavirseda — CHANGES_REQUESTED** [review]

**Review by evavirseda — APPROVED** [review]
LGTM :guitar:

**Review by brancoder — APPROVED** [review]
LGTM :+1:

**Pull request merged**
