### PR TITLE
feat(wallet-dashboard): group and display timelocked stakes

### PR DESCRIPTION
**Pull request by cpl121**
# Description of change

Please write a summary of your changes and why you made them.

## Links to any relevant issues

Closes #1085 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by marc2332 — APPROVED** [review]

**Review by begonaalvarezd — CHANGES_REQUESTED** [review]
Even though the code looks nice, I dont think it achieves what the task says, the stakes come from the query split by validator but I can delegate in 2 different epochs to the same validator and they should be grouped differently because they come from different actions on different days. As the task description says, we need to post-process the timelocked stakes so that they are grouped by epoch, delegator & label, so that if I delegate 10 objects on the same action, they show up as 1, and if I delegate another 10 objects 2 epochs later to the same validator, they again show as a new group, where the rewards and the delegated stake is the aggregation of all the timelocked stakes within the group

**Review by begonaalvarezd — COMMENTED** [review]
also, just a nit, we should not call the data "staked timelock" but rather timelocked stake / timelocked staked object / timelocked stakes / timelocked delegated stakes / timelocked staked iota ... so that we name things like the come from the SDK and the rest of the monorepo. If possible, I would try to refactor this asap 🙏🏼

**Review by brancoder — APPROVED** [review]
LGTM :+1:

**Review by brancoder — CHANGES_REQUESTED** [review]
resolve conflicts :pray:

**Review by brancoder — APPROVED** [review]
LGTM :+1:

**Review by begonaalvarezd — APPROVED** [review]

**Pull request merged**
